weights: yolov5s.pt
cfg: yolov5/model/type/yolov5s.yaml
data: scripts/dataset/coco128.yaml
hyp: scripts/hyp/hyp.scratch.yaml
epochs: 300
batch_size: 16
imgsz: 640
label_smoothing: 0.0
freeze: 0
noval: false
single_cls: false
base_dir: ./runs/train
exist_ok: true
nosave: false
evolve: null
image_weights: false
device: 0,1
workers: 8
local_rank: -1
save_dir: runs/train/yolov5s
